/*
 Waypoints - 3.1.0
Copyright © 2011-2015 Caleb Troughton
Licensed under the MIT license.
https://github.com/imakewebthings/waypoints/blog/master/licenses.txt
 Waypoints - 4.0.0
 Copyright © 2011-2015 Caleb Troughton
 Licensed under the MIT license.
 https://github.com/imakewebthings/waypoints/blob/master/licenses.txt
*/
Module.define("jquery.waypoints",["jquery"],function(){(function(){function a(e){if(!e)throw Error("No options passed to Waypoint constructor");if(!e.element)throw Error("No element option passed to Waypoint constructor");if(!e.handler)throw Error("No handler option passed to Waypoint constructor");this.key="waypoint-"+b;this.options=a.Adapter.extend({},a.defaults,e);this.element=this.options.element;this.adapter=new a.Adapter(this.element);this.callback=e.handler;this.axis=this.options.horizontal?
"horizontal":"vertical";this.enabled=this.options.enabled;this.triggerPoint=null;this.group=a.Group.findOrCreate({name:this.options.group,axis:this.axis});this.context=a.Context.findOrCreateByElement(this.options.context);a.offsetAliases[this.options.offset]&&(this.options.offset=a.offsetAliases[this.options.offset]);this.group.add(this);this.context.add(this);d[this.key]=this;b+=1}var b=0,d={};a.prototype.queueTrigger=function(a){this.group.queueTrigger(this,a)};a.prototype.trigger=function(a){this.enabled&&
this.callback&&this.callback.apply(this,a)};a.prototype.destroy=function(){this.context.remove(this);this.group.remove(this);delete d[this.key]};a.prototype.disable=function(){this.enabled=!1;return this};a.prototype.enable=function(){this.context.refresh();this.enabled=!0;return this};a.prototype.next=function(){return this.group.next(this)};a.prototype.previous=function(){return this.group.previous(this)};a.invokeAll=function(a){var b=[];for(c in d)b.push(d[c]);var c=0;for(var g=b.length;c<g;c++)b[c][a]()};
a.destroyAll=function(){a.invokeAll("destroy")};a.disableAll=function(){a.invokeAll("disable")};a.enableAll=function(){a.invokeAll("enable")};a.refreshAll=function(){a.Context.refreshAll()};a.viewportHeight=function(){return window.innerHeight||document.documentElement.clientHeight};a.viewportWidth=function(){return document.documentElement.clientWidth};a.adapters=[];a.defaults={context:window,continuous:!0,enabled:!0,group:"default",horizontal:!1,offset:0};a.offsetAliases={"bottom-in-view":function(){return this.context.innerHeight()-
this.adapter.outerHeight()},"right-in-view":function(){return this.context.innerWidth()-this.adapter.outerWidth()}};window.Waypoint=a})();(function(){function a(g){window.setTimeout(g,1E3/60)}function b(g){this.element=g;this.Adapter=f.Adapter;this.adapter=new this.Adapter(g);this.key="waypoint-context-"+d;this.didResize=this.didScroll=!1;this.oldScroll={x:this.adapter.scrollLeft(),y:this.adapter.scrollTop()};this.waypoints={vertical:{},horizontal:{}};g.waypointContextKey=this.key;e[g.waypointContextKey]=
this;d+=1;this.createThrottledScrollHandler();this.createThrottledResizeHandler()}var d=0,e={},f=window.Waypoint,c=window.onload;b.prototype.add=function(g){this.waypoints[g.options.horizontal?"horizontal":"vertical"][g.key]=g;this.refresh()};b.prototype.checkEmpty=function(){var g=this.Adapter.isEmptyObject(this.waypoints.horizontal),a=this.Adapter.isEmptyObject(this.waypoints.vertical);g&&a&&(this.adapter.off(".waypoints"),delete e[this.key])};b.prototype.createThrottledResizeHandler=function(){function g(){a.handleResize();
a.didResize=!1}var a=this;this.adapter.on("resize.waypoints",function(){a.didResize||(a.didResize=!0,f.requestAnimationFrame(g))})};b.prototype.createThrottledScrollHandler=function(){function g(){a.handleScroll();a.didScroll=!1}var a=this;this.adapter.on("scroll.waypoints",function(){if(!a.didScroll||f.isTouch)a.didScroll=!0,f.requestAnimationFrame(g)})};b.prototype.handleResize=function(){f.Context.refreshAll()};b.prototype.handleScroll=function(){var g={},a={horizontal:{newScroll:this.adapter.scrollLeft(),
oldScroll:this.oldScroll.x,forward:"right",backward:"left"},vertical:{newScroll:this.adapter.scrollTop(),oldScroll:this.oldScroll.y,forward:"down",backward:"up"}},c;for(c in a){var b=a[c],d=b.newScroll>b.oldScroll?b.forward:b.backward,f;for(f in this.waypoints[c]){var e=this.waypoints[c][f],l=b.oldScroll<e.triggerPoint,m=b.newScroll>=e.triggerPoint,n=!l&&!m;if(l&&m||n)e.queueTrigger(d),g[e.group.id]=e.group}}for(var q in g)g[q].flushTriggers();this.oldScroll={x:a.horizontal.newScroll,y:a.vertical.newScroll}};
b.prototype.innerHeight=function(){return this.element==this.element.window?f.viewportHeight():this.adapter.innerHeight()};b.prototype.remove=function(a){delete this.waypoints[a.axis][a.key];this.checkEmpty()};b.prototype.innerWidth=function(){return this.element==this.element.window?f.viewportWidth():this.adapter.innerWidth()};b.prototype.destroy=function(){var a=[];for(b in this.waypoints)for(var c in this.waypoints[b])a.push(this.waypoints[b][c]);var b=0;for(c=a.length;b<c;b++)a[b].destroy()};
b.prototype.refresh=function(){var a=this.element==this.element.window,c=a?void 0:this.adapter.offset(),b={};this.handleScroll();a={horizontal:{contextOffset:a?0:c.left,contextScroll:a?0:this.oldScroll.x,contextDimension:this.innerWidth(),oldScroll:this.oldScroll.x,forward:"right",backward:"left",offsetProp:"left"},vertical:{contextOffset:a?0:c.top,contextScroll:a?0:this.oldScroll.y,contextDimension:this.innerHeight(),oldScroll:this.oldScroll.y,forward:"down",backward:"up",offsetProp:"top"}};for(var d in a){c=
a[d];for(var e in this.waypoints[d]){var h=this.waypoints[d][e],k=h.options.offset,l=h.triggerPoint,m=0,n=null==l;h.element!==h.element.window&&(m=h.adapter.offset()[c.offsetProp]);"function"===typeof k?k=k.apply(h):"string"===typeof k&&(k=parseFloat(k),-1<h.options.offset.indexOf("%")&&(k=Math.ceil(c.contextDimension*k/100)));h.triggerPoint=m+(c.contextScroll-c.contextOffset)-k;l=l<c.oldScroll;m=h.triggerPoint>=c.oldScroll;k=l&&m;l=!l&&!m;!n&&k?(h.queueTrigger(c.backward),b[h.group.id]=h.group):
!n&&l?(h.queueTrigger(c.forward),b[h.group.id]=h.group):n&&c.oldScroll>=h.triggerPoint&&(h.queueTrigger(c.forward),b[h.group.id]=h.group)}}f.requestAnimationFrame(function(){for(var a in b)b[a].flushTriggers()});return this};b.findOrCreateByElement=function(a){return b.findByElement(a)||new b(a)};b.refreshAll=function(){for(var a in e)e[a].refresh()};b.findByElement=function(a){return e[a.waypointContextKey]};window.onload=function(){c&&c();b.refreshAll()};f.requestAnimationFrame=function(c){(window.requestAnimationFrame||
window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||a).call(window,c)};f.Context=b})();(function(){function a(a,b){return a.triggerPoint-b.triggerPoint}function b(a,b){return b.triggerPoint-a.triggerPoint}function d(a){this.name=a.name;this.axis=a.axis;this.id=this.name+"-"+this.axis;this.waypoints=[];this.clearTriggerQueues();e[this.axis][this.name]=this}var e={vertical:{},horizontal:{}},f=window.Waypoint;d.prototype.add=function(a){this.waypoints.push(a)};d.prototype.clearTriggerQueues=
function(){this.triggerQueues={up:[],down:[],left:[],right:[]}};d.prototype.flushTriggers=function(){for(var c in this.triggerQueues){var d=this.triggerQueues[c];d.sort("up"===c||"left"===c?b:a);for(var e=0,f=d.length;e<f;e+=1){var p=d[e];(p.options.continuous||e===d.length-1)&&p.trigger([c])}}this.clearTriggerQueues()};d.prototype.next=function(c){this.waypoints.sort(a);c=f.Adapter.inArray(c,this.waypoints);return c===this.waypoints.length-1?null:this.waypoints[c+1]};d.prototype.previous=function(c){this.waypoints.sort(a);
return(c=f.Adapter.inArray(c,this.waypoints))?this.waypoints[c-1]:null};d.prototype.queueTrigger=function(a,b){this.triggerQueues[b].push(a)};d.prototype.remove=function(a){a=f.Adapter.inArray(a,this.waypoints);-1<a&&this.waypoints.splice(a,1)};d.prototype.first=function(){return this.waypoints[0]};d.prototype.last=function(){return this.waypoints[this.waypoints.length-1]};d.findOrCreate=function(a){return e[a.axis][a.name]||new d(a)};f.Group=d})();(function(){function a(a){this.$element=b(a)}var b=
window.jQuery,d=window.Waypoint;b.each("innerHeight innerWidth off offset on outerHeight outerWidth scrollLeft scrollTop".split(" "),function(b,d){a.prototype[d]=function(){var a=Array.prototype.slice.call(arguments);return this.$element[d].apply(this.$element,a)}});b.each(["extend","inArray","isEmptyObject"],function(d,f){a[f]=b[f]});d.adapters.push({name:"jquery",Adapter:a});d.Adapter=a})();(function(){function a(a){return function(d,f){var c=[],e=d;a.isFunction(d)&&(e=a.extend({},f),e.handler=
d);this.each(function(){var d=a.extend({},e,{element:this});"string"===typeof d.context&&(d.context=a(this).closest(d.context)[0]);c.push(new b(d))});return c}}var b=window.Waypoint;window.jQuery&&(window.jQuery.fn.waypoint=a(window.jQuery));window.Zepto&&(window.Zepto.fn.waypoint=a(window.Zepto))})()});