name: Trigger auto deployment for learn-daily-english-words

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ master ]
    paths:
    - '**'
    - '.github/workflows/learn-daily-english-words-AutoDeployTrigger-9d3f4e82-517b-498c-b919-4457d41807f1.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.LEARNDAILYENGLISHWORDS_REGISTRY_USERNAME }}
          password: ${{ secrets.LEARNDAILYENGLISHWORDS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sad123/learn-daily-english-words:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LEARNDAILYENGLISHWORDS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n learn-daily-english-words -g AzureForStudents --server docker.io --username  ${{ secrets.LEARNDAILYENGLISHWORDS_REGISTRY_USERNAME }} --password ${{ secrets.LEARNDAILYENGLISHWORDS_REGISTRY_PASSWORD }}
            az containerapp update -n learn-daily-english-words -g AzureForStudents --image sad123/learn-daily-english-words:${{ github.sha }} --container-name learn-daily-english-words
